name = "Bear Print"
license = "MIT"
licenselink = "https://github.com/D42H5/hugo-bearprint/blob/main/LICENSE"
description = "A lightweight Hugo theme based on Bear Blog and Hugo Bear Blog, forked from clente/hugo-bearcub. It is free, multilingual, optimized for search engines, no-nonsense, responsive, light, and fast. Really fast."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/D42H5/hugo-bearprint"

# If you have a running demo of the theme.
#demosite = "https://D42H5.github.io/hugo-bearprint"

tags = ["blog", "responsive", "minimal", "personal", "dark", "multilingual"]
features = ["favicon", "seo", "no javascript", "rss", "social cards"]

# If the theme has a single author
[author]
    name = "Duncan Hogg"
    #homepage = "https://hogg.haus"

# If porting an existing theme
[original]
    author = "Caio Lente"
    homepage = "https://lente.dev"
    repo = "https://github.com/clente/hugo-bearcub"

# Hugo versions the theme supports
[module]
  [module.hugoVersion]
    min = "0.90"
